enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@mikojs/plugin-prettier-package-json.js
    spec: '@mikojs/plugin-prettier-package-json'

yarnPath: .yarn/releases/yarn-berry.cjs
