enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-build.js
    spec: "@yarnpkg/plugin-build"
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.js
    spec: "@yarnpkg/plugin-postinstall"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
