enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-utils.js
    spec: '@yarnpkg/plugin-utils'
  - path: .yarn/plugins/@yarnpkg/plugin-prettier-package-json.js
    spec: '@yarnpkg/plugin-prettier-package-json'
  - path: .yarn/plugins/@yarnpkg/plugin-flow-typed-link.js
    spec: '@yarnpkg/plugin-flow-typed-link'

yarnPath: .yarn/releases/yarn-berry.cjs
