enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@mikojs/yarn-plugin-prettier-package-json.js
    spec: '@yarnpkg/plugin-prettier-package-json'

yarnPath: .yarn/releases/yarn-berry.cjs
