enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.js
    spec: "@yarnpkg/plugin-postinstall"
  - path: .yarn/plugins/@yarnpkg/plugin-workspaces.js
    spec: "@yarnpkg/plugin-workspaces"
  - path: .yarn/plugins/@yarnpkg/plugin-build.js
    spec: "@yarnpkg/plugin-build"
  - path: .yarn/plugins/@yarnpkg/plugin-config.js
    spec: "@yarnpkg/plugin-config"
  - path: .yarn/plugins/@yarnpkg/plugin-alias.js
    spec: "@yarnpkg/plugin-alias"

yarnPath: .yarn/releases/yarn-berry.cjs
