enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@mikojs/plugin-prettier-package-json.js
    spec: '@mikojs/plugin-prettier-package-json'
  - path: .yarn/plugins/@mikojs/plugin-workspaces-link-flowconfig.js
    spec: '@mikojs/plugin-workspaces-link-flowconfig'

yarnPath: .yarn/releases/yarn-berry.cjs
