enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@mikojs/plugin-prettier-package-json.js
    spec: '@mikojs/plugin-prettier-package-json'
  - path: .yarn/plugins/@mikojs/plugin-workspaces-flow-typed.js
    spec: '@mikojs/plugin-workspaces-flow-typed'

yarnPath: .yarn/releases/yarn-berry.cjs
