enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-babel.js
    spec: "@yarnpkg/plugin-babel"
  - path: .yarn/plugins/@yarnpkg/plugin-miko.js
    spec: "@yarnpkg/plugin-miko"

yarnPath: .yarn/releases/yarn-berry.cjs
