enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@mikojs/plugin-prettier-package-json.js
    spec: '@mikojs/plugin-prettier-package-json'
  - path: .yarn/plugins/@mikojs/plugin-flow-typed-link.js
    spec: '@mikojs/plugin-flow-typed-link'

yarnPath: .yarn/releases/yarn-berry.cjs
