enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspaces.js
    spec: "@yarnpkg/plugin-workspaces"
  - path: .yarn/plugins/@yarnpkg/plugin-build.js
    spec: "@yarnpkg/plugin-build"

yarnPath: .yarn/releases/yarn-berry.cjs
