version: 2
jobs:
  test:
    working_directory: ~/repo

    docker:
      - image: node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install packages
          command: yarn install:all
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Check code style
          command: |
            yarn lint
            yarn flow

      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: coverage
          prefix: coverage

      - run:
          name: Test prod
          command: yarn prod

  deploy-beta:
    working_directory: ~/repo

    docker:
      - image: node:latest

    steps:
      - checkout

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install packages
          command: yarn install:all

      - run:
          name: publish
          command: |
            yarn prod
            bash .circleci/npm-release.sh ${CIRCLE_TAG} --npm-tag=beta

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - deploy-beta:
          context: global-env
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+(\.\d+){2}(-beta\.\d+)?/
