version: 2
defaults: &defaults
  docker:
    - image: node:latest
  working_directory: ~/repo

restore-cache: &restore-cache
  keys:
    - v1-dependencies-{{ checksum "package.json" }}
    - v1-dependencies-

save-cache: &save-cache
  paths:
    - node_modules
  key: v1-dependencies-{{ checksum "package.json" }}

install-all: &install-all
  name: Install packages
  command: yarn install:all

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-all

      - save_cache: *save-cache

      - run:
          name: Check code style
          command: |
            make babel-lint-staged
            yarn lint .
            yarn flow

      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: coverage

  deploy-beta:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-all

      - run:
          name: Pre publish
          command: |
            yarn prod
            TEST_PRODUCTION=true yarn jest ./__tests__/checkFilesInPackages.js --coverage=false

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish
          command: |
            yarn lerna publish \
              --skip-git \
              --force-publish=* \
              --repo-version ${CIRCLE_TAG} \
              --npm-tag=beta \
              --yes

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - deploy-beta:
          context: global-env
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+(\.\d+){2}(-beta\.\d+)?/
