version: 2
jobs:
  test:
    working_directory: ~/repo

    docker:
      - image: node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install packages
          command: yarn install:all
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Check code style
          command: |
            make babel-lint-staged
            yarn lint .
            yarn flow

      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: coverage

  deploy-beta:
    working_directory: ~/repo

    docker:
      - image: node:latest

    steps:
      - checkout

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install packages
          command: yarn install:all

      - run:
          name: Pre publish
          command: |
            yarn prod
            TEST_PRODUCTION=true yarn jest ./src/__tests__/checkFilesInPkg.js --coverage=false

      - run:
          name: Publish
          command: |
            yarn lerna publish \
              --skip-git \
              --force-publish=* \
              --repo-version ${CIRCLE_TAG} \
              --npm-tag=beta \
              --yes

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - deploy-beta:
          context: global-env
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+(\.\d+){2}(-beta\.\d+)?/
