name: CI

on: push

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: ./.github/actions/base
      - name: Flow check
        run: yarn miko flow
      - name: Check code style
        run: yarn miko lint
