name: CI

on: push

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '*'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Install packages
        run: yarn
      - name: Link flow files
        run: yarn miko lerna link flow
      - name: Install flow-typed
        run: yarn miko flow-typed install
      - name: Flow check
        run: yarn miko flow
      - name: Check code style
        run: yarn miko lint
      - name: Test code
        run: yarn miko jest
